name: CI/CD workflow
on:
  workflow_dispatch:
  push:
    branches: [ staging ]

jobs:
  Deploy-to-staging:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Replace '16.x' with the desired Node.js version

    - name: Install dependencies
      run: |
        echo ${{ secrets.ENV }} | base64 -d > .env
        chmod +x deployment.sh
        ./deployment.sh staging
